AllCops:
  Includes:
    - Rakefile
    - config.ru
    - Gemfile
  Excludes:
    - db/**
    - bin/**
    - config/initializers/devise.rb
    - config/environments/test.rb
    - config/enviorments/production.rb
    - config/enviorments/development.rb
    - config/initializers/secret_token.rb

Documentation:
  Enabled: false

MethodLength:
  Max: 5

ClassLength:
  Max: 100
