AllCops:
  Include:
    - Rakefile
    - config.ru
    - Gemfile
  Exclude:
    - db/**
    - bin/**
    - spec/teaspoon_env.rb
    - config/initializers/teaspoon.rb

Documentation:
  Enabled: false

MethodLength:
  Max: 5

ClassLength:
  Max: 100
