AllCops:
  Includes:
    - Rakefile
    - config.ru
    - Gemfile
  Excludes:
    - db/**
    - bin/**
    - config/initializers/devise.rb

Documentation:
  Enabled: false

MethodLength:
  Max: 5

ClassLength:
  Max: 100
